In [1]:
import pandas as pd
import numpy as ny
import matplotlib as plt

In [2]:
dataset=pd.read_csv("insurance_pre.csv")
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [3]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [4]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [5]:
indep=dataset[['age', 'bmi', 'children', 'sex_male', 'smoker_yes']]
indep

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0     False        True
1      18  33.770         1      True       False
2      28  33.000         3      True       False
3      33  22.705         0      True       False
4      32  28.880         0      True       False
...   ...     ...       ...       ...         ...
1333   50  30.970         3      True       False
1334   18  31.920         0     False       False
1335   18  36.850         0     False       False
1336   21  25.800         0     False       False
1337   61  29.070         0     False        True

[1338 rows x 5 columns]

In [6]:
dep=dataset[['charges']]
dep

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test=train_test_split(indep, dep, test_size=1/3, random_state=0)

In [12]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
X_train=sc.fit_transform(X_train)
X_test=sc.transform(X_test)
X_train

array([[-1.53963418,  0.11036616, -0.90788827, -0.98885138, -0.49929923],
       [ 0.74809711,  0.26412451, -0.0755796 ,  1.01127431,  2.00280702],
       [ 0.4621307 ,  2.13997636,  1.58903774,  1.01127431, -0.49929923],
       ...,
       [ 0.03318108, -0.90443894, -0.90788827,  1.01127431, -0.49929923],
       [-1.46814257,  0.7869029 , -0.90788827,  1.01127431, -0.49929923],
       [-0.46726014, -1.96941782, -0.0755796 , -0.98885138, -0.49929923]])

In [22]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['mse','mae','friedman_mse'], 'max_features':['auto','sqrt','log2'], 'splitter':['best','random']}

grid=GridSearchCV(DecisionTreeRegressor(), param_grid, refit=True, verbose=3, n_jobs=1)

grid.fit(X_train,Y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits
[CV 1/5] END criterion=mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=mse, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=mse, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=mse, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=mse, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=mse, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=mse, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=mse, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=mse, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=mse, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=mse, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=mse, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=mse, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=mse, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=mse, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=mse, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=mse, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=mse, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=mse, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=mse, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=mse, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=mae, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=mae, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=mae, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=mae, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=mae, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=mae, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=mae, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=mae, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=mae, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=mae, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=mae, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=mae, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=mae, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=mae, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=mae, max_features=sqrt, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=mae, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=mae, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=mae, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=mae, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=mae, max_features=sqrt, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=mae, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=mae, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=mae, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=mae, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=mae, max_features=log2, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=mae, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=mae, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=mae, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=mae, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=mae, max_features=log2, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=auto, splitter=best;, score=nan total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=auto, splitter=random;, score=nan total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.697 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.448 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.692 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.639 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=best;, score=0.631 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.521 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.572 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.779 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.648 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=sqrt, splitter=random;, score=0.514 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.682 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.260 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.723 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.638 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=best;, score=0.584 total time=   0.0s
[CV 1/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.742 total time=   0.0s
[CV 2/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.633 total time=   0.0s
[CV 3/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.471 total time=   0.0s
[CV 4/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.552 total time=   0.0s
[CV 5/5] END criterion=friedman_mse, max_features=log2, splitter=random;, score=0.516 total time=   0.0s

C:\dell\envs\aiml\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
70 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'mse' instead.

--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'criterion' parameter of DecisionTreeRegressor must be a str among {'absolute_error', 'poisson', 'friedman_mse', 'squared_error'}. Got 'mae' instead.

--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\dell\envs\aiml\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of DecisionTreeRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\dell\envs\aiml\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan        nan        nan        nan        nan
        nan        nan        nan        nan        nan        nan
        nan        nan 0.62164999 0.60699304 0.57741895 0.58278238]
  warnings.warn(

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=1,
             param_grid={'criterion': ['mse', 'mae', 'friedman_mse'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [23]:
re=grid.cv_results_

grid_predictions=grid.predict(X_test)

from sklearn.metrics import r2_score

r_score=r2_score(Y_test,grid_predictions)

print("The R_score value for best parameter{}:".format(grid.best_params_),r_score)

The R_score value for best parameter{'criterion': 'friedman_mse', 'max_features': 'sqrt', 'splitter': 'best'}: 0.6718824085179476

In [24]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000401,0.000492,0.000000,0.000000,mse,auto,best,"{'criterion': 'mse', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
1,0.000199,0.000399,0.000000,0.000000,mse,auto,random,"{'criterion': 'mse', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
2,0.000199,0.000399,0.000000,0.000000,mse,sqrt,best,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
3,0.000199,0.000398,0.000000,0.000000,mse,sqrt,random,"{'criterion': 'mse', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
4,0.000000,0.000000,0.000000,0.000000,mse,log2,best,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
5,0.000971,0.001942,0.000000,0.000000,mse,log2,random,"{'criterion': 'mse', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
6,0.000199,0.000399,0.000000,0.000000,mae,auto,best,"{'criterion': 'mae', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
7,0.000000,0.000000,0.000000,0.000000,mae,auto,random,"{'criterion': 'mae', 'max_features': 'auto', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
8,0.000598,0.000488,0.000000,0.000000,mae,sqrt,best,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
9,0.000598,0.000488,0.000000,0.000000,mae,sqrt,random,"{'criterion': 'mae', 'max_features': 'sqrt', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
10,0.000601,0.000802,0.000000,0.000000,mae,log2,best,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
11,0.000598,0.000488,0.000000,0.000000,mae,log2,random,"{'criterion': 'mae', 'max_features': 'log2', '...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
12,0.000541,0.000465,0.000000,0.000000,friedman_mse,auto,best,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
13,0.000000,0.000000,0.000000,0.000000,friedman_mse,auto,random,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,5
14,0.002180,0.001829,0.000870,0.001296,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.697360,0.448404,0.692232,0.638936,0.631318,0.621650,0.090686,1
15,0.002240,0.000504,0.000870,0.000445,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.521157,0.572362,0.779158,0.647863,0.514425,0.606993,0.098435,2
16,0.005126,0.005640,0.000399,0.000488,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.681771,0.260482,0.722685,0.638049,0.584107,0.577419,0.165022,4
17,0.003141,0.006282,0.000000,0.000000,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.741512,0.632965,0.471132,0.551948,0.516355,0.582782,0.095439,3

In [25]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
Smoker_yes_input=int(input("smoker Yes 0 or 1:"))

Age: 22
BMI: 23
Children: 2
Sex Male 0 or 1: 0
smoker Yes 0 or 1: 1

In [26]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,Smoker_yes_input]])
print("Future_Predictions={}",format(Future_Prediction))

Future_Predictions={} [48549.17835]